// PRODUCTS
export const SET_PRODUCTS="SET_PRODUCTS";
export const SELECT_PRODUCT="SELECTS_PRODUCT";
export const EMPTY_SELECTED_PRODUCT="EMPTY_SELECTED_PRODUCT";

// CART
export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";

// USER
export const SET_USER="SET_USER";
export const REMOVE_USER="REMOVE_USER";